template = ""
rev_id = 72
template_sha = "c86354124e8c85876e17c4bb07ea17433bd16f19"

[replacements]
__LICENCE__ = "GPLv3"
__REPO__ = "lang-xin-x-qda"
__UND2C__ = "qda"
__UNDEFINED__ = "Guazacapán"
__UND__ = "qda"
